name: Publicar en CDN de Azure

on:
  push:
    branches:
      - main # Cambia el nombre de la rama si es necesario

jobs:
  
  build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Instalar dependencias
      run: yarn install

    - name: Construir archivo de JavaScript
      run: npm run build
      
    - name: Log in with azure
      uses: azure/login@v1
      with: 
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Publicar en CDN de Azure
      run: |
        az storage blob upload-batch --destination $container_name --source ./dist --account-name $account_name --account-key $account_key --overwrite
        
      env:
        container_name: 'cdn'
        account_name: 'jarojasresstorage'
        account_key: ${{ secrets.AZURE_STORAGE_KEY }}

    - name: Obtener URL del CDN de Azure
      run: |
        CDN_URL=$(az cdn endpoint show --name jarojasres-tools --profile-name tools --resource-group TestGroup --query "originHostHeader" -o tsv)
        echo "CDN URL: $CDN_URL"
        
